name: backend

on:
  pull_request:
    paths:
      - "**.py"
  push:
    branches:
      - main
    paths:
      - "**.py"

jobs:
  pytest:
    strategy:
      matrix:
        python-version: ["3.11"]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    name: Pytest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python version ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
      - name: Install project
        run: poetry install
      - name: Format
        run: make fmt
      - name: Lint
        run: make lint
